const countriesList = [
  { name: "AFGHANISTAN ( AFG)", value: "AFG" },
  { name: "ALBANIA ( ALB)", value: "ALB" },
  { name: "ALGERIA ( DZA)", value: "DZA" },
  { name: "AMERICAN SAMOA ( ASM)", value: "ASM" },
  { name: "ANDORRA ( AND)", value: "AND" },
  { name: "ANGOLA ( AGO)", value: "AGO" },
  { name: "ANGUILLA ( AIA)", value: "AIA" },
  { name: "ANTARCTICA ( ATA)", value: "ATA" },
  { name: "ANTIGUA AND BARBUDA ( ATG)", value: "ATG" },
  { name: "ARGENTINA ( ARG)", value: "ARG" },
  { name: "ARMENIA ( ARM)", value: "ARM" },
  { name: "ARUBA ( ABW)", value: "ABW" },
  { name: "AUSTRALIA ( AUS)", value: "AUS" },
  { name: "AUSTRIA ( AUT)", value: "AUT" },
  { name: "AZERBAIJAN ( AZE)", value: "AZE" },
  { name: "BAHAMAS ( BHS)", value: "BHS" },
  { name: "BAHRAIN ( BHR)", value: "BHR" },
  { name: "BANGLADESH ( BGD)", value: "BGD" },
  { name: "BARBADOS ( BRB)", value: "BRB" },
  { name: "BELARUS ( BLR)", value: "BLR" },
  { name: "BELGIUM ( BEL)", value: "BEL" },
  { name: "BELIZE ( BLZ)", value: "BLZ" },
  { name: "BENIN ( BEN)", value: "BEN" },
  { name: "BERMUDA ( BMU)", value: "BMU" },
  { name: "BOLIVIA ( BOL)", value: "BOL" },
  { name: "BOSNIA AND HERZEGOVINA ( BIH)", value: "BIH" },
  { name: "BOTSWANA ( BWA)", value: "BWA" },
  { name: "BRAZIL ( BRA)", value: "BRA" },
  { name: "BRUNEI DARUSSALAM ( BRN)", value: "BRN" },
  { name: "BULGARIA ( BGR)", value: "BGR" },
  { name: "BURKINA FASO ( BFA)", value: "BFA" },
  { name: "BURUNDI ( BDI)", value: "BDI" },
  { name: "CAMBODIA ( KHM)", value: "KHM" },
  { name: "CAMEROON ( CMR)", value: "CMR" },
  { name: "CANADA ( CAN)", value: "CAN" },
  { name: "CAPE VERDE ( CPV)", value: "CPV" },
  { name: "CAYMAN ISLANDS ( CYM)", value: "CYM" },
  { name: "CENTRAL AFRICAN REPUBLIC ( CAF)", value: "CAF" },
  { name: "CHAD ( TCD)", value: "TCD" },
  { name: "CHILE ( CHL)", value: "CHL" },
  { name: "CHINA ( CHN)", value: "CHN" },
  { name: "CHRISTMAS ISLAND ( CXR)", value: "CXR" },
  { name: "COCOS (KEELING), ISLANDS ( CCK)", value: "CCK" },
  { name: "COLOMBIA ( COL)", value: "COL" },
  { name: "COMOROS ( COM)", value: "COM" },
  { name: "CONGO, REPUBLIC OF (BRAZZAVILLE), ( COG)", value: "COG" },
  { name: "DEMOCRATIC REPUBLIC OF THE CONGO (KINSHASA), ( COD)", value: "COD" },
  { name: "COOK ISLANDS ( COK)", value: "COK" },
  { name: "COSTA RICA ( CRI)", value: "CRI" },
  { name: "IVORY COAST ( CIV)", value: "CIV" },
  { name: "CROATIA ( HRV)", value: "HRV" },
  { name: "CUBA ( CUB)", value: "CUB" },
  { name: "CYPRUS ( CYP)", value: "CYP" },
  { name: "CZECH REPUBLIC ( CZE)", value: "CZE" },
  { name: "DENMARK ( DNK)", value: "DNK" },
  { name: "DJIBOUTI ( DJI)", value: "DJI" },
  { name: "DOMINICA ( DMA)", value: "DMA" },
  { name: "DOMINICAN REPUBLIC ( DOM)", value: "DOM" },
  { name: "ECUADOR ( ECU)", value: "ECU" },
  { name: "EGYPT ( EGY)", value: "EGY" },
  { name: "EL SALVADOR ( SLV)", value: "SLV" },
  { name: "EQUATORIAL GUINEA ( GNQ)", value: "GNQ" },
  { name: "ERITREA ( ERI)", value: "ERI" },
  { name: "ESTONIA ( EST)", value: "EST" },
  { name: "ETHIOPIA ( ETH)", value: "ETH" },
  { name: "FALKLAND ISLANDS (MALVINAS), ( FLK)", value: "FLK" },
  { name: "FAROE ISLANDS ( FRO)", value: "FRO" },
  { name: "FIJI ( FJI)", value: "FJI" },
  { name: "FINLAND ( FIN)", value: "FIN" },
  { name: "FRANCE ( FRA)", value: "FRA" },
  { name: "FRENCH GUIANA ( GUF)", value: "GUF" },
  { name: "FRENCH POLYNESIA ( PYF)", value: "PYF" },
  { name: "FRENCH SOUTHERN TERRITORIES (ATF), ( FRA)", value: "ATF" },
  { name: "GABON ( GAB)", value: "GAB" },
  { name: "GAMBIA ( GMB)", value: "GMB" },
  { name: "GEORGIA ( GEO)", value: "GEO" },
  { name: "GERMANY ( DEU)", value: "DEU" },
  { name: "GHANA ( GHA)", value: "GHA" },
  { name: "GIBRALTAR ( GIB)", value: "GIB" },
  { name: "GREECE ( GRC)", value: "GRC" },
  { name: "GREENLAND ( GRL)", value: "GRL" },
  { name: "GRENADA ( GRD)", value: "GRD" },
  { name: "GUADELOUPE ( GLP)", value: "GLP" },
  { name: "GUAM ( GUM)", value: "GUM" },
  { name: "GUATEMALA ( GTM)", value: "GTM" },
  { name: "GUERNSEY ( GGY)", value: "GGY" },
  { name: "GUINEA ( GIN)", value: "GIN" },
  { name: "GUINEA-BISSAU ( GNB)", value: "GNB" },
  { name: "GUYANA ( GUY)", value: "GUY" },
  { name: "HAITI ( HTI)", value: "HTI" },
  { name: "HONDURAS ( HND)", value: "HND" },
  { name: "HONG KONG ( HKG)", value: "HKG" },
  { name: "HUNGARY ( HUN)", value: "HUN" },
  { name: "ICELAND ( ISL)", value: "ISL" },
  { name: "INDIA ( IND)", value: "IND" },
  { name: "INDONESIA ( IDN)", value: "IDN" },
  { name: "IRAN (IRAN, ISLAMIC REPUBLIC OF), ( IRN)", value: "IRN" },
  { name: "IRAQ ( IRQ)", value: "IRQ" },
  { name: "IRELAND ( IRL)", value: "IRL" },
  { name: "ISLE OF MAN ( IMN)", value: "IMN" },
  { name: "ISRAEL ( ISR)", value: "ISR" },
  { name: "ITALY ( ITA)", value: "ITA" },
  { name: "JAMAICA ( JAM)", value: "JAM" },
  { name: "JAPAN ( JPN)", value: "JPN" },
  { name: "JERSEY ( JEY)", value: "JEY" },
  { name: "JORDAN ( JOR)", value: "JOR" },
  { name: "KAZAKHSTAN ( KAZ)", value: "KAZ" },
  { name: "KENYA ( KEN)", value: "KEN" },
  { name: "KIRIBATI ( KIR)", value: "KIR" },
  { name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF (KP), ( PRK)", value: "PRK" },
  { name: "KOREA, REPUBLIC OF (KR), ( KOR)", value: "KOR" },
  { name: "KUWAIT ( KWT)", value: "KWT" },
  { name: "KYRGYZSTAN ( KGZ)", value: "KGZ" },
  { name: "LATVIA ( LVA)", value: "LVA" },
  { name: "LEBANON ( LBN)", value: "LBN" },
  { name: "LESOTHO ( LSO)", value: "LSO" },
  { name: "LIBERIA ( LBR)", value: "LBR" },
  { name: "LIBYA ( LBY)", value: "LBY" },
  { name: "LIECHTENSTEIN ( LIE)", value: "LIE" },
  { name: "LITHUANIA ( LTU)", value: "LTU" },
  { name: "LUXEMBOURG ( LUX)", value: "LUX" },
  { name: "MACAU ( MAC)", value: "MAC" },
  { name: "NORTH MACEDONIA (MKD), ( MKD)", value: "MKD" },
  { name: "MADAGASCAR ( MDG)", value: "MDG" },
  { name: "MALAWI ( MWI)", value: "MWI" },
  { name: "MALAYSIA ( MYS)", value: "MYS" },
];
export default countriesList;
